import type { Movie } from '../types/movie';

export const starterMovies: Movie[] = [
  {
    adult: false,
    backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
    genre_ids: [28, 12, 878],
    id: 27205,
    original_language: 'en',
    original_title: 'Inception',
    overview:
      '타인의 꿈에 들어가 생각을 훔치는 전문가가 불가능에 가까운 마지막 임무에 도전한다.',
    popularity: 83.5,
    poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    release_date: '2010-07-15',
    title: '인셉션',
    video: false,
    vote_average: 8.4,
    vote_count: 36500,
  },
  {
    adult: false,
    backdrop_path: '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: 'ko',
    original_title: '기생충',
    overview:
      '전원백수 가족이 부유한 박 사장 가족과 얽히며 예측하기 어려운 사건에 휘말린다.',
    popularity: 73.2,
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    release_date: '2019-05-30',
    title: '기생충',
    video: false,
    vote_average: 8.5,
    vote_count: 18500,
  },
  {
    adult: false,
    backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: 'ja',
    original_title: '千と千尋の神隠し',
    overview:
      '낯선 세계에 들어선 치히로가 부모를 구하고 집으로 돌아가기 위해 성장해 나간다.',
    popularity: 68.4,
    poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    release_date: '2001-07-20',
    title: '센과 치히로의 행방불명',
    video: false,
    vote_average: 8.5,
    vote_count: 17100,
  },
  {
    adult: false,
    backdrop_path: '/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
    genre_ids: [12, 18, 878],
    id: 157336,
    original_language: 'en',
    original_title: 'Interstellar',
    overview:
      '인류의 미래를 찾기 위해 우주로 향한 탐사대가 시간과 사랑의 경계를 넘나든다.',
    popularity: 79.1,
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    release_date: '2014-11-05',
    title: '인터스텔라',
    video: false,
    vote_average: 8.4,
    vote_count: 35400,
  },
];
